# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infogeneral',
            old_name='semetre',
            new_name='semestre',
        ),
        migrations.AddField(
            model_name='infogeneral',
            name='estatura',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='infogeneral',
            name='nombre',
            field=models.CharField(default='Juanito', max_length=50),
        ),
        migrations.AlterField(
            model_name='infogeneral',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2),
        ),
        migrations.AlterField(
            model_name='infogeneral',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
